# Although pre-commit is not designed for monorepo,
# This is the suggested format from its contributor
# https://github.com/pre-commit/pre-commit/issues/466#issuecomment-274282684

# configure shared hooks that you want to run on all repositories here
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: |
          (?x)^(
            20_helm/
          )
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
      - id: check-added-large-files
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.3
    hooks:
      - id: check-github-workflows
      - id: check-github-actions
  # For hooks that only apply to specific repositories, list them below
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: helmlint
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint-docker
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3.12
