# https://taskfile.dev

version: "3"

dotenv: [".env", "{{.HOME}}/.env", "{{.USER_WORKING_DIR}}/.env"]

vars:
  AWS_ECR_PROFILE: "{{.AWS_ECR_PROFILE}}"
  DOCKER_REGISTRY_REGION: "us-east-2"
  IMAGE: "{{.DOCKER_REGISTRY}}/cloudtrail:test"

tasks:
  authenticate:
    status:
      - aws sts get-caller-identity --query \"Account\" --profile {{.AWS_ECR_PROFILE}}
    cmds:
      - aws sso login --profile {{.AWS_ECR_PROFILE}}
      # - assume --un {{.AWS_ECR_PROFILE}}

  docker-authenticate:
    deps:
      - task: authenticate
        vars: { AWS_ECR_PROFILE: "{{.AWS_ECR_PROFILE}}" }
    cmds:
      - aws ecr get-login-password --region {{.DOCKER_REGISTRY_REGION}} --profile {{.AWS_ECR_PROFILE}} | docker login --username AWS --password-stdin {{.DOCKER_REGISTRY}} || true
  default:
    cmds:
      - poetry install
      - task: build
  build:
    vars:
      DOCKERFILE: '{{ default "Dockerfile" .DOCKERFILE }}'
    cmds:
      - docker build -f {{ .DOCKERFILE }} -t {{ .IMAGE }} .
  build-basic:
    cmds:
      - task: build
        vars: { DOCKERFILE: Dockerfile.basic }
  build-optimized:
    cmds:
      - task: build
        vars:
          DOCKERFILE: Dockerfile.optimized
  build-production:
    cmds:
      - task: build
  docker-push:
    deps: [docker-authenticate]
    cmds:
      - docker push {{ .IMAGE }}
