replicaCount: 2

image:
  repository: 157206707803.dkr.ecr.us-east-2.amazonaws.com/cloudtrail-ai:test
  tag: test
  pullPolicy: Always

service:
  name: python-poetry-app
  type: ClusterIP
  port: 5000
  targetPort: 5000

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: python-poetry-app.local
      paths: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  APP_MODE: development
