replicaCount: 1

image:
  repository: 157206707803.dkr.ecr.us-east-2.amazonaws.com/cloudtrail-ai:test
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: python-poetry-app
  type: ClusterIP
  port: 5000
  targetPort: 5000

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: python-poetry-app.local
      paths: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
